FROM node:24.5.0-alpine AS base

WORKDIR /usr/src/app



FROM base AS deps

COPY package.json package-lock.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm ci --ignore-scripts



FROM base AS builder

COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY package.json ./


# RUN npm run prebuild || true
RUN npm run build


FROM base AS development
ENV NODE_ENV=development
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .

CMD ["npm", "run", "start"]

FROM base AS prod-deps
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev --ignore-scripts

FROM base AS production
ENV NODE_ENV=production
USER node

COPY --chown=node:node --from=prod-deps /usr/src/app/node_modules ./node_modules
COPY --chown=node:node --from=builder   /usr/src/app/dist        ./
COPY --chown=node:node package.json ./


CMD [ "npm", "run", "start" ]