name: Production Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/')

    uses: asc-base/acs-website-infra/.github/workflows/release-prod-nextjs.yml@main

    with:
      release-branch: ${{ github.event.pull_request.head.ref }}
      release-sha: ${{ github.event.pull_request.head.sha }}
      main-sha: ${{ github.event.pull_request.merge_commit_sha }}

    secrets: inherit
