name: Release

on:
  push:
    branches:
      - "release/**"

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: asc-base/gitops/.github/workflows/release-rc.yml@main
    secrets: inherit
